//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENBpresetAssistant.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PresetStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresetStr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENBpresetAssistant.Lang.PresetStr", typeof(PresetStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DETAIL 的本地化字符串。
        /// </summary>
        internal static string Btn_Detail {
            get {
                return ResourceManager.GetString("Btn_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RETURN 的本地化字符串。
        /// </summary>
        internal static string Btn_Return {
            get {
                return ResourceManager.GetString("Btn_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Falied To Get Presets Info 的本地化字符串。
        /// </summary>
        internal static string Falied_To_Get_Presets_Info {
            get {
                return ResourceManager.GetString("Falied_To_Get_Presets_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CoreVersion 的本地化字符串。
        /// </summary>
        internal static string Intro_CoreVersion {
            get {
                return ResourceManager.GetString("Intro_CoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENBPresetName 的本地化字符串。
        /// </summary>
        internal static string Intro_ENBPresetName {
            get {
                return ResourceManager.GetString("Intro_ENBPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill In Contained ENB Core  的本地化字符串。
        /// </summary>
        internal static string Intro_FillDefaultCore {
            get {
                return ResourceManager.GetString("Intro_FillDefaultCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seems Good 的本地化字符串。
        /// </summary>
        internal static string Intro_Preset_Available {
            get {
                return ResourceManager.GetString("Intro_Preset_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maybe Somthing Wrong 的本地化字符串。
        /// </summary>
        internal static string Intro_Preset_Unavailable {
            get {
                return ResourceManager.GetString("Intro_Preset_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PresetName 的本地化字符串。
        /// </summary>
        internal static string Intro_PresetName {
            get {
                return ResourceManager.GetString("Intro_PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Installed Core 的本地化字符串。
        /// </summary>
        internal static string Intro_SelectInstalledCore {
            get {
                return ResourceManager.GetString("Intro_SelectInstalledCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set As Root 的本地化字符串。
        /// </summary>
        internal static string Intro_SetRoot {
            get {
                return ResourceManager.GetString("Intro_SetRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contained Core 的本地化字符串。
        /// </summary>
        internal static string Intro_UseDefaultCore {
            get {
                return ResourceManager.GetString("Intro_UseDefaultCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed Core 的本地化字符串。
        /// </summary>
        internal static string Intro_UseInstalledCore {
            get {
                return ResourceManager.GetString("Intro_UseInstalledCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Preset Managed 的本地化字符串。
        /// </summary>
        internal static string No_Preset_Managed {
            get {
                return ResourceManager.GetString("No_Preset_Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset Added 的本地化字符串。
        /// </summary>
        internal static string Preset_Added {
            get {
                return ResourceManager.GetString("Preset_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available 的本地化字符串。
        /// </summary>
        internal static string State_Available {
            get {
                return ResourceManager.GetString("State_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmanaged ENB Is Running . Please Clean And Try Later 的本地化字符串。
        /// </summary>
        internal static string Unmanaged_ENB {
            get {
                return ResourceManager.GetString("Unmanaged_ENB", resourceCulture);
            }
        }
    }
}
