//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENBpresetAssistant.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsStr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENBpresetAssistant.Lang.SettingsStr", typeof(SettingsStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed To Create New Folder 的本地化字符串。
        /// </summary>
        internal static string Failed_To_Create_New_Folder {
            get {
                return ResourceManager.GetString("Failed_To_Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed To Save 的本地化字符串。
        /// </summary>
        internal static string Failed_To_Save {
            get {
                return ResourceManager.GetString("Failed_To_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Created 的本地化字符串。
        /// </summary>
        internal static string Folder_Created {
            get {
                return ResourceManager.GetString("Folder_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not TESV Folder 的本地化字符串。
        /// </summary>
        internal static string Not_TESV_Folder {
            get {
                return ResourceManager.GetString("Not_TESV_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path Does Not Exist 的本地化字符串。
        /// </summary>
        internal static string Path_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Path_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paths 的本地化字符串。
        /// </summary>
        internal static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settins Saved 的本地化字符串。
        /// </summary>
        internal static string Settins_Saved {
            get {
                return ResourceManager.GetString("Settins_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage 的本地化字符串。
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Presets &amp; Cores Storge Here 的本地化字符串。
        /// </summary>
        internal static string StorageHint {
            get {
                return ResourceManager.GetString("StorageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TESV 的本地化字符串。
        /// </summary>
        internal static string TESV {
            get {
                return ResourceManager.GetString("TESV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Elder Scrolls V Path 的本地化字符串。
        /// </summary>
        internal static string TESVHint {
            get {
                return ResourceManager.GetString("TESVHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
    }
}
