//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENBpresetAssistant.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ID {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ID() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENBpresetAssistant.Data.ID", typeof(ID).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string Chinense {
            get {
                return ResourceManager.GetString("Chinense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en-US 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 isDark 的本地化字符串。
        /// </summary>
        public static string ST_isDark {
            get {
                return ResourceManager.GetString("ST_isDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string ST_Language {
            get {
                return ResourceManager.GetString("ST_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StoragePath 的本地化字符串。
        /// </summary>
        public static string ST_StoragePath {
            get {
                return ResourceManager.GetString("ST_StoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TESVPath 的本地化字符串。
        /// </summary>
        public static string ST_TESVPath {
            get {
                return ResourceManager.GetString("ST_TESVPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThemeColor 的本地化字符串。
        /// </summary>
        public static string ST_ThemeColor {
            get {
                return ResourceManager.GetString("ST_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CoreStr 的本地化字符串。
        /// </summary>
        public static string StrRes_Core {
            get {
                return ResourceManager.GetString("StrRes_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainStr 的本地化字符串。
        /// </summary>
        public static string StrRes_Main {
            get {
                return ResourceManager.GetString("StrRes_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PresetStr 的本地化字符串。
        /// </summary>
        public static string StrRes_Preset {
            get {
                return ResourceManager.GetString("StrRes_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SettingsStr 的本地化字符串。
        /// </summary>
        public static string StrRes_Settings {
            get {
                return ResourceManager.GetString("StrRes_Settings", resourceCulture);
            }
        }
    }
}
